################################################
################ CI Config #####################
################################################

# Language setting http://docs.shippable.com/ci/nodejs-continuous-integration/
language: node_js
node_js:
  - 8.4.0

runtime:
  nodePool: demo_aarch64

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - DOCKER_REPO=dh_aarch64_app
    - DOCKER_ACC=aye0aye # {account name}
build:
  pre_ci_boot:
    image_name: drydock/aarch64_u16nodall
    image_tag: v6.2.4

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - node --version
    - npm install
    - export XUNIT_FILE=shippable/testresults/result.xml
    - mkdir -p shippable/testresults
    - npm test
    - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - export IMG_NAME=$DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER
    - docker build -t $IMG_NAME .
    - docker push $IMG_NAME
  on_success:
    # save the new image state for use later in the pipeline
    - shipctl put_resource_state $DOCKER_REPO versionName $BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: demo_dh
      type: docker

  notifications:
    - integrationName: email
      type: email
      recipients:
        - avi@shippable.com
      sendConsoleLogs: true
      sendCoverageReports: true
      on_pull_request: never

#---------------------------------------------------------------#
#------------------ Pipeline Resources -------------------------#
#---------------------------------------------------------------#
resources:
# Docker Image
  - name: dh_aarch64_app
    type: image
    integration: demo_dh # replace with your integration name
    versionTemplate:
      sourceName: "aye0aye/dh_aarch64_app" # replace with your Hub URL
      isPull: false
      versionName: latest

#---------------------------------------------------------------#
#--------------------   Pipeline Jobs   ------------------------#
#---------------------------------------------------------------#
jobs:

# runCI job that builds and pushes artifact using Shippable CI
  - name: aarch64App_runCI
    type: runCI
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - OUT: dh_aarch64_app
    flags:
      - Arm
