################################################
################ CI Config #####################
################################################

# Language setting http://docs.shippable.com/ci/nodejs-continuous-integration/
language: node_js
node_js:
  - 8.4.0

runtime:
  nodePool: demo_aarch64

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - DOCKER_REPO=dh_aarch64_app
    - DOCKER_ACC=aye0aye # {account name}
build:
  pre_ci_boot:
    image_name: drydock/aarch64_u16nodall
    image_tag: v6.2.4

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - node --version
    - npm install
    - export XUNIT_FILE=shippable/testresults/result.xml
    - mkdir -p shippable/testresults
    - npm test
    - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - export IMG_NAME=$DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER
    - docker build -t $IMG_NAME .
    - docker push $IMG_NAME
  on_success:
    # save the new image state for use later in the pipeline
    - shipctl put_resource_state $DOCKER_REPO versionName $BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: demo_dh
      type: docker

  notifications:
    - integrationName: email
      type: email
      recipients:
        - avi@shippable.com
      sendConsoleLogs: true
      sendCoverageReports: true
      on_pull_request: never


################################################
################ CD Config #####################
################################################
resources:
# Docker Image
  - name: dh_aarch64_app
    type: image
    integration: demo_dh # replace with your integration name
    versionTemplate:
      sourceName: "aye0aye/dh_aarch64_app" # replace with your Hub URL
      isPull: false
      versionName: latest

## Parameters for CD
#  - name: app_params
#    type: params
#    versionTemplate:
#      params:
#        RUNMODE: "test"
#        REGION: "Hong Kong"
#        TITLE: "welcome to demo blog"
#        ENDPOINT: "147.75.67.14"
#        USERNAME: "root"
#
## PEM key integration to be used to ssh into deployment host
#  - name: deploy_key
#    type: integration
#    integration: aarch_demo

jobs:
# runCI job that builds and pushes artifact using Shippable CI
  - name: aarch64App_runCI
    type: runCI
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - OUT: dh_aarch64_app
    flags:
      - Arm

## runSH job that that deploys a docker container
#  - name: aarch64App_deploy
#    type: runSh
#    runtime:
#      nodePool: demo_aarch64
#    steps:
#      - IN: deploy_key
#      - IN: dh_aarch64_app
#      - IN: app_params
#        switch: off
#      - TASK:
#          name: deploying_app
#          script:
#            - pushd $(shipctl get_resource_meta deploy_key)
#            - export APP_NAME="blog"
#            - cat integration.json | jq -r '.key' > key.pem
#            - chmod 600 key.pem
#            - ssh-add key.pem
#            - ssh-add -L
#            - export APP_IMG=$(shipctl get_resource_version_key dh_aarch64_app sourceName)
#            - export APP_TAG=$(shipctl get_resource_version_name dh_aarch64_app)
#            - ssh $USERNAME@$ENDPOINT "sudo docker rm -f $APP_NAME || true"
#            - ssh $USERNAME@$ENDPOINT "sudo docker pull  $APP_IMG:$APP_TAG"
#            - ssh $USERNAME@$ENDPOINT "sudo docker run -d -p 3000:3000 --env RELEASE='$RUNMODE' --env RUN_MODE='$RUNMODE' --env REGION='$REGION' --env APP_TITLE='$TITLE' --name='$APP_NAME' $APP_IMG:$APP_TAG"
#            - popd
